### ISSUE TITLE
Questions about validating the certificate that client receives from the server with intermediate CAs

### ISSUE THREAD

**Issue by ComptonAlvaro** [stewartadam/dotnet-x509-certificate-verification#1]
Hello.

I was working in an application that use self signed certificates (CA, server and client) and i was thinking how to validate the certificate that the client receives from the server.

In my case, I distrubute the CA and the server certificates with the client application. Then I have to implement the method that validate the server certificate. In my case, the code is this:

```
private bool ValidarCertificadoServidor(object paramSender, X509Certificate? paramCertificadoServidor, X509Chain? paramCadenaCertificadosServidor, SslPolicyErrors paramErrores)
{
    paramCadenaCertificadosServidor!.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;
    paramCadenaCertificadosServidor.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
    paramCadenaCertificadosServidor.ChainPolicy.CustomTrustStore.Add(_certificadoCA);


    X509Certificate2 miCertificaServidorConvertido = paramCadenaCertificadosServidor.ChainElements.ElementAt(0).Certificate;
    return paramCadenaCertificadosServidor.Build(miCertificaServidorConvertido);
}
```

In this case, I don't create a new chain, just I modificate the chain that I receive from the server, setting that I want to set the custom root trust.

In the custom trust store, I add the CA that the client has, it is the expected CA. So I don't use the CA that is include in the chain received from the server.

When I build it passing as parameter the first element of the chain received from the server, that is the certificate from the server, I get true. So it works. If I build without configurating it, I get false.

Well, my doubt is what is validated in the build. I guess that it validate that the server certificate is issued by my CA, but I could be wrong.

If I am right, it is an important validation, but I guess that still it is needed to compare the thumbprint of the server certificate that is distribute with the client application and the server certificate that is received from the server.

I think that this is needed because perhaps someone could stole the server certificate and the CA, after all, both are publics certificates. So comparing the thumbprints, I am ensuring that really the certificate of the server is the expected certificate.

I am right, that I should to compare the thumbprints of the certificates or is it not needed because it is validate in the build of the chain? But i guess it is not possible in the build because the chain that is received from the server doesn't know which is the server certificate that the client expects.

Thanks.

**Comment by stewartadam** [comment]
Hello!

> In the custom trust store, I add the CA that the client has, it is the expected CA. So I don't use the CA that is include in the chain received from the server.

Certificate verification generally requires you to populate all intermediate chains as well, so in the custom root trust store, you should populate the intermediate certificates plus your root CA.

> Well, my doubt is what is validated in the build. 

It may be worth looking at the `PrintX509VerificationResults` method in [certvalidate-common.csx](https://github.com/stewartadam/dotnet-x509-certificate-verification/blob/main/certvalidate-common.csx) for details - `.build()` will return true/false as well as some additional status details to provide context on how it asserted the X509 chain.

In your case, if you have a specific CA that signed your leaf certificate and would like to verify that, then ensure that the `.build()` result is `true` and there are no special flags like `PartialChain` that were returned.

> If I am right, it is an important validation, but I guess that still it is needed to compare the thumbprint of the server certificate that is distribute with the client application and the server certificate that is received from the server.

Correct, particularly for .NET Core 3.1 as this verification is not performed by `.build()`. However with .NET 5+ and the CustomRootTrust, it *only* uses certificates from that root trust which sometimes means this manual verification is not necessary.

However if you have intermediate CAs involved (which from your post appears so), then you may want to perform this check to verify that the chain reached all the way to your root CA and a didn't just stop at one of the intermediate CAs.

Let me know if you have further questions!

**Comment by stewartadam** [comment]
I'll close this as answered but feel free to reopen if you have further questions!
